# compose.yaml

services:
  app:
    container_name: iuranku
    build:
      context: .
      dockerfile: .docker/Dockerfile
    ports:
      - "8003:80" # HTTP
      # - "443:443" # HTTPS
      # - "443:443/udp" # HTTP/3
    # volumes:
      # - ./:/app/public
      # - caddy_data:/data
      # - caddy_config:/config
    # comment the following line in production, it allows to have nice human-readable logs in dev
    # tty: true
    networks:
      - app
      - database_mysql

# Volumes needed for Caddy certificates and configuration
# volumes:
#   caddy_data:
#   caddy_config:

networks:
  app:
    driver: "bridge"
  database_mysql:
    external: true
